const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, 'js', 'translations.js');
let content = fs.readFileSync(file, 'utf8');

// Extract the object text
const startIdx = content.indexOf('{');
const endIdx = content.lastIndexOf('};') + 1;
const objText = content.substring(startIdx, endIdx);

let translations;
eval('translations = ' + objText);

const newKeys = {
  en: {
    guide_reboot_title: "Project Reboot IsraelServices Free Internal Guides",
    guide_reboot_works: "Works on Season 2 - Season 19",
    guide_reboot_step1: "Step 1: Download the .rar file and open UuuClient.exe, then open Reboot.",
    guide_reboot_step2: "Step 2: In UuuClient, select your game process (the name is something like fortnitelauncher win64, you can't miss it).",
    guide_reboot_step3: "Step 3: Add the .dll right above where you selected the process, then find the .dll, double-click it, then inject. You're all set!",
    guide_reboot_fun: "Have fun trolling your friends with it.",
    
    guide_rm_title: "Red Match 2 — Setup Guide",
    guide_rm_h1: "1. Install Redmatch 2",
    guide_rm_s1_1: "Open Steam and install Redmatch 2 (free game)",
    guide_rm_s1_2: "Make sure it's in the default location:",
    guide_rm_s1_3: "Launch the game once to make sure it works, then close it",
    guide_rm_h2: "2. Install",
    guide_rm_s2_1: "Run start.bat (!AND BE SURE THAT THE DLL IS IN THE SAME FOLDER!)",
    guide_rm_s2_2: "Start Redmatch 2 from Steam normally",
    guide_rm_s2_3: "A window appears asking for a key",
    guide_rm_h3: "3. The Key",
    guide_rm_s3_1: "Enter the key that you got from the linkvertise",
    guide_rm_s3_2: "Click Authenticate",
    guide_rm_h4: "In-Game Controls",
    guide_rm_c1: "Open/close menu",
    guide_rm_c2: "Unload the cheat completely",
    guide_rm_c3: "Aimbot (when enabled in menu)"
  },
  fr: {
    guide_reboot_title: "Project Reboot IsraelServices Guides Internes Gratuits",
    guide_reboot_works: "Fonctionne sur la Saison 2 - Saison 19",
    guide_reboot_step1: "Étape 1 : Téléchargez le fichier .rar et ouvrez UuuClient.exe, puis ouvrez Reboot.",
    guide_reboot_step2: "Étape 2 : Dans UuuClient, sélectionnez le processus de votre jeu (le nom ressemble à fortnitelauncher win64, vous ne pouvez pas le rater).",
    guide_reboot_step3: "Étape 3 : Ajoutez la .dll juste au-dessus de là où vous avez sélectionné le processus, puis trouvez la .dll, double-cliquez dessus, puis injectez. Tout est prêt !",
    guide_reboot_fun: "Amusez-vous bien à troller vos amis avec ça.",
    guide_rm_title: "Red Match 2 — Guide d'Installation",
    guide_rm_h1: "1. Installer Redmatch 2",
    guide_rm_s1_1: "Ouvrez Steam et installez Redmatch 2 (jeu gratuit)",
    guide_rm_s1_2: "Assurez-vous qu'il est dans l'emplacement par défaut :",
    guide_rm_s1_3: "Lancez le jeu une fois pour vous assurer qu'il fonctionne, puis fermez-le",
    guide_rm_h2: "2. Installer",
    guide_rm_s2_1: "Exécutez start.bat (!ET ASSUREZ-VOUS QUE LA DLL EST DANS LE MÊME DOSSIER!)",
    guide_rm_s2_2: "Démarrez Redmatch 2 depuis Steam normalement",
    guide_rm_s2_3: "Une fenêtre apparaît demandant une clé",
    guide_rm_h3: "3. La Clé",
    guide_rm_s3_1: "Entrez la clé que vous avez obtenue depuis linkvertise",
    guide_rm_s3_2: "Cliquez sur Authentifier",
    guide_rm_h4: "Contrôles en Jeu",
    guide_rm_c1: "Ouvrir/fermer le menu",
    guide_rm_c2: "Décharger le cheat complètement",
    guide_rm_c3: "Aimbot (lorsque activé dans le menu)"
  },
  ru: {
    guide_reboot_title: "Project Reboot IsraelServices Бесплатные Внутренние Руководства",
    guide_reboot_works: "Работает в Сезоне 2 - Сезоне 19",
    guide_reboot_step1: "Шаг 1: Загрузите файл .rar и откройте UuuClient.exe, затем откройте Reboot.",
    guide_reboot_step2: "Шаг 2: В UuuClient выберите процесс вашей игры (имя примерно fortnitelauncher win64, вы не ошибетесь).",
    guide_reboot_step3: "Шаг 3: Добавьте .dll чуть выше того места, где вы выбрали процесс, найдите .dll, дважды щелкните по нему, затем инжект. Готово!",
    guide_reboot_fun: "Веселитесь, тролля друзей с этим.",
    guide_rm_title: "Red Match 2 — Руководство по Установке",
    guide_rm_h1: "1. Установить Redmatch 2",
    guide_rm_s1_1: "Откройте Steam и установите Redmatch 2 (бесплатная игра)",
    guide_rm_s1_2: "Убедитесь, что она находится в месте по умолчанию:",
    guide_rm_s1_3: "Запустите игру один раз, чтобы убедиться, что она работает, затем закройте",
    guide_rm_h2: "2. Установка",
    guide_rm_s2_1: "Запустите start.bat (!И УБЕДИТЕСЬ, ЧТО DLL НАХОДИТСЯ В ТОЙ ЖЕ ПАПКЕ!)",
    guide_rm_s2_2: "Запустите Redmatch 2 из Steam как обычно",
    guide_rm_s2_3: "Появится окно с запросом ключа",
    guide_rm_h3: "3. Ключ",
    guide_rm_s3_1: "Введите ключ, который вы получили из linkvertise",
    guide_rm_s3_2: "Нажмите Аутентификация",
    guide_rm_h4: "Управление в Игре",
    guide_rm_c1: "Открыть/закрыть меню",
    guide_rm_c2: "Полностью выгрузить чит",
    guide_rm_c3: "Аимбот (при включении в меню)"
  },
  pt: {
    guide_reboot_title: "Guias Internos Gratuitos Project Reboot IsraelServices",
    guide_reboot_works: "Funciona da Temporada 2 à Temporada 19",
    guide_reboot_step1: "Passo 1: Baixe o arquivo .rar e abra UuuClient.exe, depois abra o Reboot.",
    guide_reboot_step2: "Passo 2: No UuuClient, selecione o processo do jogo (o nome é algo como fortnitelauncher win64).",
    guide_reboot_step3: "Passo 3: Adicione a .dll logo acima de onde selecionou o processo, clique duas vezes e injete. Tudo pronto!",
    guide_reboot_fun: "Divirta-se trollando seus amigos com isso.",
    guide_rm_title: "Red Match 2 — Guia de Configuração",
    guide_rm_h1: "1. Instalar Redmatch 2",
    guide_rm_s1_1: "Abra a Steam e instale Redmatch 2 (jogo grátis)",
    guide_rm_s1_2: "Certifique-se de que está no local padrão:",
    guide_rm_s1_3: "Inicie o jogo uma vez para garantir que funciona, e feche-o",
    guide_rm_h2: "2. Instalar",
    guide_rm_s2_1: "Execute start.bat (!E CERTIFIQUE-SE DE QUE A DLL ESTÁ NA MESMA PASTA!)",
    guide_rm_s2_2: "Inicie Redmatch 2 pela Steam normalmente",
    guide_rm_s2_3: "Uma janela pedirá uma chave",
    guide_rm_h3: "3. A Chave",
    guide_rm_s3_1: "Insira a chave obtida no linkvertise",
    guide_rm_s3_2: "Clique em Autenticar",
    guide_rm_h4: "Controles no Jogo",
    guide_rm_c1: "Abrir/fechar menu",
    guide_rm_c2: "Descarregar o cheat completamente",
    guide_rm_c3: "Aimbot (quando ativado no menu)"
  },
  es: {
    guide_reboot_title: "Guías Internas Gratuitas Project Reboot IsraelServices",
    guide_reboot_works: "Funciona en Temporada 2 - Temporada 19",
    guide_reboot_step1: "Paso 1: Descarga el archivo .rar, abre UuuClient.exe y abre Reboot.",
    guide_reboot_step2: "Paso 2: En UuuClient, selecciona el proceso (fortnitelauncher win64).",
    guide_reboot_step3: "Paso 3: Añade la .dll donde seleccionaste el proceso, doble clic e inyecta. ¡Listo!",
    guide_reboot_fun: "Diviértete trolleando a tus amigos con esto.",
    guide_rm_title: "Red Match 2 — Guía de Configuración",
    guide_rm_h1: "1. Instalar Redmatch 2",
    guide_rm_s1_1: "Abre Steam e instala Redmatch 2 (juego gratis)",
    guide_rm_s1_2: "Asegúrate de que está en la ruta por defecto:",
    guide_rm_s1_3: "Inicia el juego una vez para verificar y ciérralo",
    guide_rm_h2: "2. Instalar",
    guide_rm_s2_1: "Ejecuta start.bat (!Y ASEGÚRATE DE QUE LA DLL ESTÉ EN LA MISMA CARPETA!)",
    guide_rm_s2_2: "Inicia Redmatch 2 desde Steam normalmente",
    guide_rm_s2_3: "Aparecerá una ventana pidiendo una clave",
    guide_rm_h3: "3. La Clave",
    guide_rm_s3_1: "Introduce la clave de linkvertise",
    guide_rm_s3_2: "Haz clic en Autenticar",
    guide_rm_h4: "Controles en Juego",
    guide_rm_c1: "Abrir/cerrar menú",
    guide_rm_c2: "Descargar el cheat por completo",
    guide_rm_c3: "Aimbot (cuando está activado)"
  },
  de: {
    guide_reboot_title: "Project Reboot IsraelServices Kostenlose Interne Anleitungen",
    guide_reboot_works: "Funktioniert in Season 2 - Season 19",
    guide_reboot_step1: "Schritt 1: Lade die .rar herunter, öffne UuuClient.exe, dann öffne Reboot.",
    guide_reboot_step2: "Schritt 2: In UuuClient wähle deinen Spielprozess (fortnitelauncher win64).",
    guide_reboot_step3: "Schritt 3: Füge die .dll hinzu, doppelklicke und injiziere. Fertig!",
    guide_reboot_fun: "Viel Spaß beim Trollen deiner Freunde damit.",
    guide_rm_title: "Red Match 2 — Einrichtungsanleitung",
    guide_rm_h1: "1. Redmatch 2 Installieren",
    guide_rm_s1_1: "Öffne Steam und installiere Redmatch 2 (kostenlos)",
    guide_rm_s1_2: "Stelle sicher, dass es am Standardort ist:",
    guide_rm_s1_3: "Starte das Spiel einmal, um sicherzustellen, dass es funktioniert",
    guide_rm_h2: "2. Installieren",
    guide_rm_s2_1: "Führe start.bat aus (!DIE DLL MUSS IM SELBEN ORDNER SEIN!)",
    guide_rm_s2_2: "Starte Redmatch 2 ganz normal über Steam",
    guide_rm_s2_3: "Ein Fenster fragt nach einem Schlüssel",
    guide_rm_h3: "3. Der Schlüssel",
    guide_rm_s3_1: "Gib den Schlüssel von linkvertise ein",
    guide_rm_s3_2: "Klicke auf Authentifizieren",
    guide_rm_h4: "Steuerung im Spiel",
    guide_rm_c1: "Menü öffnen/schließen",
    guide_rm_c2: "Cheat komplett entladen",
    guide_rm_c3: "Aimbot (wenn aktiviert)"
  },
  sv: {
    guide_reboot_title: "Project Reboot IsraelServices Gratis Interna Guider",
    guide_reboot_works: "Fungerar på Säsong 2 - Säsong 19",
    guide_reboot_step1: "Steg 1: Ladda ner .rar, öppna UuuClient.exe, öppna sedan Reboot.",
    guide_reboot_step2: "Steg 2: I UuuClient, välj spelprocessen (fortnitelauncher win64).",
    guide_reboot_step3: "Steg 3: Lägg till .dll, dubbelklicka och injicera. Klar!",
    guide_reboot_fun: "Ha kul med att trolla dina vänner.",
    guide_rm_title: "Red Match 2 — Installationsguide",
    guide_rm_h1: "1. Installera Redmatch 2",
    guide_rm_s1_1: "Öppna Steam och installera Redmatch 2 (gratis spel)",
    guide_rm_s1_2: "Se till att det är på standardplatsen:",
    guide_rm_s1_3: "Starta spelet en gång för att se till att det fungerar",
    guide_rm_h2: "2. Installera",
    guide_rm_s2_1: "Kör start.bat (!OCH SE TILL ATT DLL ÄR I SAMMA MAPP!)",
    guide_rm_s2_2: "Starta Redmatch 2 via Steam som vanligt",
    guide_rm_s2_3: "Ett fönster ber om en nyckel",
    guide_rm_h3: "3. Nyckeln",
    guide_rm_s3_1: "Ange nyckeln från linkvertise",
    guide_rm_s3_2: "Klicka på Autentisera",
    guide_rm_h4: "Spelkontroller",
    guide_rm_c1: "Öppna/stäng meny",
    guide_rm_c2: "Ladda ur fusket helt",
    guide_rm_c3: "Aimbot (när aktiverat)"
  },
  no: {
    guide_reboot_title: "Project Reboot IsraelServices Gratis Interne Guider",
    guide_reboot_works: "Fungerer på Sesong 2 - Sesong 19",
    guide_reboot_step1: "Trinn 1: Last ned .rar, åpne UuuClient.exe, åpne så Reboot.",
    guide_reboot_step2: "Trinn 2: I UuuClient, velg spillprosessen (fortnitelauncher win64).",
    guide_reboot_step3: "Trinn 3: Legg til .dll, dobbeltklikk og injiser. Ferdig!",
    guide_reboot_fun: "Ha det gøy med å trolle vennene dine med dette.",
    guide_rm_title: "Red Match 2 — Oppsettsguide",
    guide_rm_h1: "1. Installer Redmatch 2",
    guide_rm_s1_1: "Åpne Steam og installer Redmatch 2 (gratis spill)",
    guide_rm_s1_2: "Pass på at det er på standardplasseringen:",
    guide_rm_s1_3: "Start spillet en gang for å sikre at det fungerer",
    guide_rm_h2: "2. Installer",
    guide_rm_s2_1: "Kjør start.bat (!OG SØRG FOR AT DLL ER I SAMME MAPPE!)",
    guide_rm_s2_2: "Start Redmatch 2 fra Steam normalt",
    guide_rm_s2_3: "Et vindu ber om en nøkkel",
    guide_rm_h3: "3. Nøkkelen",
    guide_rm_s3_1: "Skriv inn nøkkelen fra linkvertise",
    guide_rm_s3_2: "Klikk Autentiser",
    guide_rm_h4: "Spillkontroller",
    guide_rm_c1: "Åpne/lukke meny",
    guide_rm_c2: "Last ut jukset helt",
    guide_rm_c3: "Aimbot (når aktivert)"
  },
  hi: {
    guide_reboot_title: "प्रोजेक्ट रीबूट इज़राइल सर्विसेज फ्री इंटरनल गाइड्स",
    guide_reboot_works: "सीजन 2 - सीजन 19 पर काम करता है",
    guide_reboot_step1: "चरण 1: .rar डाउनलोड करें, UuuClient.exe खोलें, फिर Reboot खोलें।",
    guide_reboot_step2: "चरण 2: गेम प्रोसेस चुनें (fortnitelauncher win64)।",
    guide_reboot_step3: "चरण 3: .dll जोड़ें, डबल-क्लिक करें और इंजेक्ट करें। तैयार!",
    guide_reboot_fun: "अपने दोस्तों को ट्रोल करने का मज़ा लें।",
    guide_rm_title: "Red Match 2 — सेटअप गाइड",
    guide_rm_h1: "1. Redmatch 2 स्थापित करें",
    guide_rm_s1_1: "स्टीम खोलें और Redmatch 2 (मुफ्त गेम) इंस्टॉल करें",
    guide_rm_s1_2: "सुनिश्चित करें कि यह डिफ़ॉल्ट स्थान पर है:",
    guide_rm_s1_3: "जांचने के लिए गेम को एक बार लॉन्च करें",
    guide_rm_h2: "2. इंस्टॉल",
    guide_rm_s2_1: "start.bat चलाएं (!और सुनिश्चित करें कि DLL उसी फ़ोल्डर में है!)",
    guide_rm_s2_2: "स्टीम से Redmatch 2 सामान्य रूप से शुरू करें",
    guide_rm_s2_3: "एक विंडो कुंजी मांगेगी",
    guide_rm_h3: "3. कुंजी",
    guide_rm_s3_1: "लिंकवर्टाइज से प्राप्त कुंजी दर्ज करें",
    guide_rm_s3_2: "प्रमाणीकृत पर क्लिक करें",
    guide_rm_h4: "इन-गेम नियंत्रण",
    guide_rm_c1: "मेनू खोलें/बंद करें",
    guide_rm_c2: "चीट को पूरी तरह से हटा दें",
    guide_rm_c3: "ऐमबॉट (जब मेनू में सक्षम हो)"
  },
  ar: {
    guide_reboot_title: "أدلة المشروع الداخلية المجانية Reboot IsraelServices",
    guide_reboot_works: "يعمل في الموسم 2 - الموسم 19",
    guide_reboot_step1: "الخطوة 1: قم بتنزيل .rar وافتح UuuClient.exe ، ثم افتح Reboot.",
    guide_reboot_step2: "الخطوة 2: حدد عملية اللعبة (fortnitelauncher win64).",
    guide_reboot_step3: "الخطوة 3: أضف .dll ، وانقر نقرًا مزدوجًا ثم حقن. أنت جاهز!",
    guide_reboot_fun: "استمتع بخداع أصدقائك بهذا.",
    guide_rm_title: "Red Match 2 — دليل الإعداد",
    guide_rm_h1: "1. قم بتثبيت Redmatch 2",
    guide_rm_s1_1: "افتح Steam وقم بتثبيت Redmatch 2 (لعبة مجانية)",
    guide_rm_s1_2: "تأكد من أنه في الموقع الافتراضي:",
    guide_rm_s1_3: "قم بتشغيل اللعبة مرة واحدة للتأكد من أنها تعمل",
    guide_rm_h2: "2. تثبيت",
    guide_rm_s2_1: "قم بتشغيل start.bat (!وتأكد من أن ملف DLL موجود في نفس المجلد!)",
    guide_rm_s2_2: "ابدأ تشغيل Redmatch 2 من Steam بشكل طبيعي",
    guide_rm_s2_3: "تظهر نافذة تطلب مفتاحًا",
    guide_rm_h3: "3. المفتاح",
    guide_rm_s3_1: "أدخل المفتاح الذي حصلت عليه من linkvertise",
    guide_rm_s3_2: "انقر فوق مصادقة",
    guide_rm_h4: "عناصر التحكم داخل اللعبة",
    guide_rm_c1: "فتح / إغلاق القائمة",
    guide_rm_c2: "قم بإلغاء تحميل الغش بالكامل",
    guide_rm_c3: "Aimbot (عند تمكينه في القائمة)"
  },
  tr: {
    guide_reboot_title: "Project Reboot IsraelServices Ücretsiz İç Rehberler",
    guide_reboot_works: "Sezon 2 - Sezon 19'da çalışır",
    guide_reboot_step1: "Adım 1: .rar'ı indirin, UuuClient.exe'yi açın, ardından Reboot'u açın.",
    guide_reboot_step2: "Adım 2: Oyun sürecini seçin (fortnitelauncher win64).",
    guide_reboot_step3: "Adım 3: .dll'i ekleyin, çift tıklayın ve inject edin. Hazırsınız!",
    guide_reboot_fun: "Bununla arkadaşlarınızı trollerken iyi eğlenceler.",
    guide_rm_title: "Red Match 2 — Kurulum Rehberi",
    guide_rm_h1: "1. Redmatch 2'yi Yükle",
    guide_rm_s1_1: "Steam'i açın ve Redmatch 2'yi yükleyin (ücretsiz oyun)",
    guide_rm_s1_2: "Varsayılan konumda olduğundan emin olun:",
    guide_rm_s1_3: "Çalıştığından emin olmak için oyunu bir kez başlatın",
    guide_rm_h2: "2. Kurulum",
    guide_rm_s2_1: "start.bat'ı çalıştırın (!VE DLL'İN AYNI KLASÖRDE OLDUĞUNDAN EMİN OLUN!)",
    guide_rm_s2_2: "Redmatch 2'yi Steam'den normal olarak başlatın",
    guide_rm_s2_3: "Bir anahtar soran bir pencere belirir",
    guide_rm_h3: "3. Anahtar",
    guide_rm_s3_1: "linkvertise'dan aldığınız anahtarı girin",
    guide_rm_s3_2: "Doğrula'ya tıklayın",
    guide_rm_h4: "Oyun İçi Kontroller",
    guide_rm_c1: "Menüyü aç/kapat",
    guide_rm_c2: "Hileyi tamamen boşalt",
    guide_rm_c3: "Aimbot (menüde etkinleştirildiğinde)"
  }
};

for (const lang in translations) {
  if (newKeys[lang]) {
    for (const key in newKeys[lang]) {
      translations[lang][key] = newKeys[lang][key];
    }
  }
}

const newOutput = "const translations = " + JSON.stringify(translations, null, 2) + ";\n\n" +
  content.substring(endIdx).trimStart();

fs.writeFileSync(file, newOutput, 'utf8');
console.log('Translations updated successfully');
